Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

FM_default: # This is a config template
    model: FM
    dataset_id: TBD
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    regularizer: 0
    batch_size: 10000
    embedding_dim: 10
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

FM_avazu_x4_003_a62c6000: &default_avazu
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    embedding_dropout: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: FM
    model_id: FM_base
    model_root: ./Avazu/FM_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
    emb_activation: linear
    symmetric: false
    concat_emb: false
    gamma: 1
    small_transformation: false

FM_avazu:
    <<: *default_avazu

FM_avazu_gen: &default_avazu_gen
    <<: *default_avazu
    concat_emb: true
    emb_activation: relu
    gamma: 6

FM_criteo_x1_001_bea53d16: &default_criteo
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FM
    model_id: FM_base
    model_root: ./Criteo/FM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    regularizer: 5.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    emb_activation: linear
    symmetric: false
    concat_emb: false
    gamma: 1
    small_transformation: false

FM_criteo:
    <<: *default_criteo

FM_criteo_gen: &default_criteo_gen
    <<: *default_criteo
    emb_activation: relu
    concat_emb: true
    gamma: 0.1