Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DCNv2_default: # This is a config template
    model: DCNv2
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    model_structure: parallel
    use_low_rank_mixture: False
    low_rank: 32
    num_experts: 4
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 40
    stacked_dnn_hidden_units: [500, 500, 500]
    parallel_dnn_hidden_units: [500, 500, 500]
    dnn_activations: relu
    num_cross_layers: 3
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

DCNv2_criteo_x1_001_28c60688: &default_criteo
    batch_norm: false
    batch_size: 4096
    data_block_size: -1
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_activations: relu
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Criteo/DCNv2_criteo_x1/
    model_structure: parallel
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    num_cross_layers: 3
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [500, 500, 500]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    stacked_dnn_hidden_units: [400, 400, 400]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
    emb_activation: linear
    symmetric: false
    concat_emb: false
    gamma: 1
    small_transformation: false
    cross_drop: 0.
    use_gen_rst: false

DCNv2_criteo:
    <<: *default_criteo

DCNv2_criteo_gen: &default_criteo_gen
    <<: *default_criteo
    emb_activation: relu
    concat_emb: true
    gamma: 0.01
    use_gen_rst: true
    gen_residual: true
    cross_drop: 0.1

CrossNet_criteo:
    <<: *default_criteo
    model_structure: crossnet_only

CrossNet_criteo_gen:
    <<: *default_criteo_gen
    emb_activation: relu
    model_structure: crossnet_only


DCNv2_avazu_x4_011_19794dc6: &default_avazu
    batch_norm: false
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    dnn_activations: relu
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    low_rank: 32
    metrics: [AUC, logloss]
    model: DCNv2
    model_id: DCNv2_base
    model_root: ./Avazu/DCNv2_avazu_x4_001/
    model_structure: parallel
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_cross_layers: 5
    num_experts: 4
    num_workers: 3
    optimizer: adam
    parallel_dnn_hidden_units: [2000, 2000, 2000, 2000]
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    stacked_dnn_hidden_units: [2000, 2000, 2000, 2000]
    task: binary_classification
    use_hdf5: true
    use_low_rank_mixture: false
    verbose: 1
    emb_activation: linear
    symmetric: false
    concat_emb: false
    gamma: 1
    small_transformation: false

DCNv2_avazu:
    << : *default_avazu

DCNv2_avazu_gen: &default_avazu_gen
    << : *default_avazu
    emb_activation: relu
    concat_emb: true
    gamma: 8
    gen_residual: true
    use_gen_rst: true


CrossNet_avazu:
    << : *default_avazu
    model_structure: crossnet_only

CrossNet_avazu_gen:
    << : *default_avazu_gen
    model_structure: crossnet_only