Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

xDeepFM_test:
    model: xDeepFM
    dataset_id: tiny_npz
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-8
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    dnn_hidden_units: [64, 32]
    cin_layer_units: [10, 10]
    hidden_activations: relu
    net_dropout: 0
    batch_norm: False
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

xDeepFM_default: # This is a config template
    model: xDeepFM
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 40
    dnn_hidden_units: [500, 500, 500]
    cin_hidden_units: [32, 32, 32]
    hidden_activations: relu
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

xDeepFM_avazu_x4_001_579eef11: &default_avazu
    batch_norm: false
    batch_size: 10000
    cin_hidden_units: [276]
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    dnn_hidden_units: [500, 500, 500]
    embedding_dim: 16
    embedding_dropout: 0
    embedding_regularizer: 0
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Avazu/xDeepFM_avazu_x4_001/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    workers: 3
    emb_activation: linear
    symmetric: false
    concat_emb: false
    gamma: 1

xDeepFM_avazu:
    <<: *default_avazu

xDeepFM_avazu_gen:
    <<: *default_avazu
    emb_activation: relu
    concat_emb: true
    gamma: 6

xDeepFM_criteo_x1_001_e08ec7de: &default_criteo
    batch_norm: false
    batch_size: 4096
    cin_hidden_units: [16, 16]
    dataset_id: criteo_x1_7b681156
    debug: false
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 1.0e-05
    epochs: 100
    every_x_epochs: 1
    hidden_activations: relu
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: xDeepFM
    model_id: xDeepFM_base
    model_root: ./Criteo/xDeepFM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    emb_activation: linear
    symmetric: false
    concat_emb: false
    gamma: 1

xDeepFM_criteo:
    <<: *default_criteo

xDeepFM_criteo_gen: &default_criteo_gen
    <<: *default_criteo
    emb_activation: relu
    concat_emb: true
    gamma: 0.01