Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

FmFM_test:
    model: FmFM
    dataset_id: tiny_npz
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    regularizer: 0
    field_interaction_type: matrixed
    batch_size: 128
    embedding_dim: 4
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

FmFM_default: # This is a config template
    model: FmFM
    dataset_id: TBD
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    regularizer: 0
    field_interaction_type: matrixed
    batch_size: 10000
    embedding_dim: 10
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

FmFM_criteo_x1_001_9ba4938b: &default_criteo
    batch_size: 4096
    dataset_id: criteo_x1_7b681156
    debug: false
    embedding_dim: 10
    epochs: 100
    every_x_epochs: 1
    field_interaction_type: matrixed
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FmFM
    model_id: FmFM_base
    model_root: ./Criteo/FmFM_criteo_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    emb_activation: linear
    symmetric: false
    concat_emb: false
    gamma: 1

FmFM_criteo:
    <<: *default_criteo

FmFM_criteo_gen:
    <<: *default_criteo
    emb_activation: relu
    symmetric: false
    concat_emb: true
    gamma: 6

FmFM_avazu_x4_002_a09a4da9: &default_avazu
    batch_size: 10000
    dataset_id: avazu_x4_3bbbc4c9
    debug: false
    embedding_dim: 16
    epochs: 100
    every_x_epochs: 1
    field_interaction_type: matrixed
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [AUC, logloss]
    model: FmFM
    model_id: FmFM_base
    model_root: ./Avazu/FmFM_avazu_x1/
    monitor: AUC
    monitor_mode: max
    num_workers: 3
    optimizer: adam
    partition_block_size: -1
    patience: 2
    pickle_feature_encoder: true
    regularizer: 1.0e-06
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    emb_activation: linear
    symmetric: false
    concat_emb: false
    gamma: 1

FmFM_avazu:
    <<: *default_avazu

FmFM_avazu_gen:
    <<: *default_avazu
    emb_activation: relu
    concat_emb: true
    gamma: 36